name: bliss
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.3

# Add regular dependencies here.
dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
